// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: eye_asset_250730

#include "../ui.h"

lv_obj_t * uic_defaultStandBy;
lv_obj_t * ui_defaultStandBy = NULL;
lv_obj_t * ui_eyeblinkLeft = NULL;
lv_obj_t * ui_eyeblinkRight = NULL;
lv_obj_t * ui_rougeLeft = NULL;
lv_obj_t * ui_rougeRight = NULL;
lv_obj_t * ui_mouthstandBy = NULL;
// event funtions
void ui_event_defaultStandBy(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        eyeblink_Animation(ui_eyeblinkRight, 4000);
        eyeblink_Animation(ui_eyeblinkLeft, 4000);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        lv_anim_delete(ui_eyeblinkRight, NULL);
        lv_anim_delete(ui_eyeblinkLeft, NULL);
    }
    if(event_code == LV_EVENT_KEY) {
        _ui_screen_change(&ui_talking, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_talking_screen_init);
    }
}

// build funtions

void ui_defaultStandBy_screen_init(void)
{
    ui_defaultStandBy = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_defaultStandBy, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_defaultStandBy, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_darkMode);
    ui_object_set_themeable_style_property(ui_defaultStandBy, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_darkMode);
    lv_obj_set_style_bg_image_src(ui_defaultStandBy, &ui_img_background_black_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_eyeblinkLeft = lv_image_create(ui_defaultStandBy);
    lv_image_set_src(ui_eyeblinkLeft, &ui_img_eye_blink_01_png);
    lv_obj_set_width(ui_eyeblinkLeft, LV_SIZE_CONTENT);   /// 76
    lv_obj_set_height(ui_eyeblinkLeft, LV_SIZE_CONTENT);    /// 123
    lv_obj_set_x(ui_eyeblinkLeft, -69);
    lv_obj_set_y(ui_eyeblinkLeft, -20);
    lv_obj_set_align(ui_eyeblinkLeft, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_eyeblinkLeft, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_eyeblinkLeft, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_eyeblinkRight = lv_image_create(ui_defaultStandBy);
    lv_image_set_src(ui_eyeblinkRight, &ui_img_eye_blink_01_png);
    lv_obj_set_width(ui_eyeblinkRight, LV_SIZE_CONTENT);   /// 76
    lv_obj_set_height(ui_eyeblinkRight, LV_SIZE_CONTENT);    /// 123
    lv_obj_set_x(ui_eyeblinkRight, 69);
    lv_obj_set_y(ui_eyeblinkRight, -20);
    lv_obj_set_align(ui_eyeblinkRight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_eyeblinkRight, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_eyeblinkRight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_rougeLeft = lv_image_create(ui_defaultStandBy);
    lv_image_set_src(ui_rougeLeft, &ui_img_eff_rouge_png);
    lv_obj_set_width(ui_rougeLeft, LV_SIZE_CONTENT);   /// 27
    lv_obj_set_height(ui_rougeLeft, LV_SIZE_CONTENT);    /// 8
    lv_obj_set_x(ui_rougeLeft, -72);
    lv_obj_set_y(ui_rougeLeft, 74);
    lv_obj_set_align(ui_rougeLeft, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rougeLeft, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_rougeLeft, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_rougeRight = lv_image_create(ui_defaultStandBy);
    lv_image_set_src(ui_rougeRight, &ui_img_eff_rouge_png);
    lv_obj_set_width(ui_rougeRight, LV_SIZE_CONTENT);   /// 27
    lv_obj_set_height(ui_rougeRight, LV_SIZE_CONTENT);    /// 8
    lv_obj_set_x(ui_rougeRight, 68);
    lv_obj_set_y(ui_rougeRight, 74);
    lv_obj_set_align(ui_rougeRight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rougeRight, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_rougeRight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_mouthstandBy = lv_image_create(ui_defaultStandBy);
    lv_image_set_src(ui_mouthstandBy, &ui_img_mouth_standby_png);
    lv_obj_set_width(ui_mouthstandBy, LV_SIZE_CONTENT);   /// 23
    lv_obj_set_height(ui_mouthstandBy, LV_SIZE_CONTENT);    /// 13
    lv_obj_set_x(ui_mouthstandBy, -3);
    lv_obj_set_y(ui_mouthstandBy, 93);
    lv_obj_set_align(ui_mouthstandBy, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mouthstandBy, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_mouthstandBy, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_defaultStandBy, ui_event_defaultStandBy, LV_EVENT_ALL, NULL);
    uic_defaultStandBy = ui_defaultStandBy;

}

void ui_defaultStandBy_screen_destroy(void)
{
    if(ui_eyeblinkLeft) lv_anim_delete(ui_eyeblinkLeft, NULL);
    if(ui_eyeblinkRight) lv_anim_delete(ui_eyeblinkRight, NULL);

    if(ui_defaultStandBy) lv_obj_del(ui_defaultStandBy);

    // NULL screen variables
    uic_defaultStandBy = NULL;
    ui_defaultStandBy = NULL;
    ui_eyeblinkLeft = NULL;
    ui_eyeblinkRight = NULL;
    ui_rougeLeft = NULL;
    ui_rougeRight = NULL;
    ui_mouthstandBy = NULL;

}
