// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: eye_asset_250730

#ifndef UI_DEFAULTSTANDBY_H
#define UI_DEFAULTSTANDBY_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_defaultStandBy
extern void ui_defaultStandBy_screen_init(void);
extern void ui_defaultStandBy_screen_destroy(void);
extern void ui_event_defaultStandBy(lv_event_t * e);
extern lv_obj_t * ui_defaultStandBy;
extern lv_obj_t * ui_eyeblinkLeft;
extern lv_obj_t * ui_eyeblinkRight;
extern lv_obj_t * ui_rougeLeft;
extern lv_obj_t * ui_rougeRight;
extern lv_obj_t * ui_mouthstandBy;
// CUSTOM VARIABLES
extern lv_obj_t * uic_defaultStandBy;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
