// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: eye_asset_250730

#ifndef UI_TALKING_H
#define UI_TALKING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_talking
extern void ui_talking_screen_init(void);
extern void ui_talking_screen_destroy(void);
extern void ui_event_talking(lv_event_t * e);
extern lv_obj_t * ui_talking;
extern lv_obj_t * ui_eyeblinkLeft1;
extern lv_obj_t * ui_eyeblinkRight1;
extern lv_obj_t * ui_rougeLeft1;
extern lv_obj_t * ui_rougeRight1;
extern lv_obj_t * ui_mouthTalking;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
