// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: eye_asset_250730

#include "../ui.h"

lv_obj_t * ui_talking = NULL;
lv_obj_t * ui_eyeblinkLeft1 = NULL;
lv_obj_t * ui_eyeblinkRight1 = NULL;
lv_obj_t * ui_rougeLeft1 = NULL;
lv_obj_t * ui_rougeRight1 = NULL;
lv_obj_t * ui_mouthTalking = NULL;
// event funtions
void ui_event_talking(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        eyeblink_Animation(ui_eyeblinkRight1, 4000);
        eyeblink_Animation(ui_eyeblinkLeft1, 4000);
        mouthTalking_Animation(ui_mouthTalking, 0);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        lv_anim_delete(ui_eyeblinkRight1, NULL);
        lv_anim_delete(ui_eyeblinkLeft1, NULL);
        lv_anim_delete(ui_mouthTalking, NULL);
    }
    if(event_code == LV_EVENT_KEY) {
        _ui_screen_change(&ui_defaultStandBy, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_defaultStandBy_screen_init);
    }
}

// build funtions

void ui_talking_screen_init(void)
{
    ui_talking = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_talking, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_talking, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_darkMode);
    ui_object_set_themeable_style_property(ui_talking, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_darkMode);
    lv_obj_set_style_bg_image_src(ui_talking, &ui_img_background_black_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_eyeblinkLeft1 = lv_image_create(ui_talking);
    lv_image_set_src(ui_eyeblinkLeft1, &ui_img_eye_blink_01_png);
    lv_obj_set_width(ui_eyeblinkLeft1, LV_SIZE_CONTENT);   /// 76
    lv_obj_set_height(ui_eyeblinkLeft1, LV_SIZE_CONTENT);    /// 123
    lv_obj_set_x(ui_eyeblinkLeft1, -69);
    lv_obj_set_y(ui_eyeblinkLeft1, -20);
    lv_obj_set_align(ui_eyeblinkLeft1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_eyeblinkLeft1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_eyeblinkLeft1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_eyeblinkRight1 = lv_image_create(ui_talking);
    lv_image_set_src(ui_eyeblinkRight1, &ui_img_eye_blink_01_png);
    lv_obj_set_width(ui_eyeblinkRight1, LV_SIZE_CONTENT);   /// 76
    lv_obj_set_height(ui_eyeblinkRight1, LV_SIZE_CONTENT);    /// 123
    lv_obj_set_x(ui_eyeblinkRight1, 69);
    lv_obj_set_y(ui_eyeblinkRight1, -20);
    lv_obj_set_align(ui_eyeblinkRight1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_eyeblinkRight1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_eyeblinkRight1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_rougeLeft1 = lv_image_create(ui_talking);
    lv_image_set_src(ui_rougeLeft1, &ui_img_eff_rouge_png);
    lv_obj_set_width(ui_rougeLeft1, LV_SIZE_CONTENT);   /// 27
    lv_obj_set_height(ui_rougeLeft1, LV_SIZE_CONTENT);    /// 8
    lv_obj_set_x(ui_rougeLeft1, -72);
    lv_obj_set_y(ui_rougeLeft1, 74);
    lv_obj_set_align(ui_rougeLeft1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rougeLeft1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_rougeLeft1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_rougeRight1 = lv_image_create(ui_talking);
    lv_image_set_src(ui_rougeRight1, &ui_img_eff_rouge_png);
    lv_obj_set_width(ui_rougeRight1, LV_SIZE_CONTENT);   /// 27
    lv_obj_set_height(ui_rougeRight1, LV_SIZE_CONTENT);    /// 8
    lv_obj_set_x(ui_rougeRight1, 68);
    lv_obj_set_y(ui_rougeRight1, 74);
    lv_obj_set_align(ui_rougeRight1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rougeRight1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_rougeRight1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_mouthTalking = lv_image_create(ui_talking);
    lv_image_set_src(ui_mouthTalking, &ui_img_mouth_talking_01_png);
    lv_obj_set_width(ui_mouthTalking, LV_SIZE_CONTENT);   /// 29
    lv_obj_set_height(ui_mouthTalking, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_mouthTalking, 0);
    lv_obj_set_y(ui_mouthTalking, 93);
    lv_obj_set_align(ui_mouthTalking, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mouthTalking, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_mouthTalking, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_talking, ui_event_talking, LV_EVENT_ALL, NULL);

}

void ui_talking_screen_destroy(void)
{
    if(ui_eyeblinkLeft1) lv_anim_delete(ui_eyeblinkLeft1, NULL);
    if(ui_eyeblinkRight1) lv_anim_delete(ui_eyeblinkRight1, NULL);
    if(ui_mouthTalking) lv_anim_delete(ui_mouthTalking, NULL);

    if(ui_talking) lv_obj_del(ui_talking);

    // NULL screen variables
    ui_talking = NULL;
    ui_eyeblinkLeft1 = NULL;
    ui_eyeblinkRight1 = NULL;
    ui_rougeLeft1 = NULL;
    ui_rougeRight1 = NULL;
    ui_mouthTalking = NULL;

}
