/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_EMOJI_FILES           15
#define MMAP_EMOJI_CHECKSUM        0x1C7C

enum MMAP_EMOJI_LISTS {
    MMAP_EMOJI_ANGRY_ONE_AAF = 0,        /*!< angry_one.aaf */
    MMAP_EMOJI_DIZZY_ONE_AAF = 1,        /*!< dizzy_one.aaf */
    MMAP_EMOJI_ENJOY_ONE_AAF = 2,        /*!< enjoy_one.aaf */
    MMAP_EMOJI_HAPPY_ONE_AAF = 3,        /*!< happy_one.aaf */
    MMAP_EMOJI_IDLE_ONE_AAF = 4,        /*!< idle_one.aaf */
    MMAP_EMOJI_LISTEN_AAF = 5,        /*!< listen.aaf */
    MMAP_EMOJI_SAD_ONE_AAF = 6,        /*!< sad_one.aaf */
    MMAP_EMOJI_SHOCKED_ONE_AAF = 7,        /*!< shocked_one.aaf */
    MMAP_EMOJI_THINKING_ONE_AAF = 8,        /*!< thinking_one.aaf */
    MMAP_EMOJI_ICON_BATTERY_BIN = 9,        /*!< icon_Battery.bin */
    MMAP_EMOJI_ICON_WIFI_FAILED_BIN = 10,        /*!< icon_WiFi_failed.bin */
    MMAP_EMOJI_ICON_MIC_BIN = 11,        /*!< icon_mic.bin */
    MMAP_EMOJI_ICON_SPEAKER_ZZZ_BIN = 12,        /*!< icon_speaker_zzz.bin */
    MMAP_EMOJI_ICON_WIFI_BIN = 13,        /*!< icon_wifi.bin */
    MMAP_EMOJI_KAITI_TTF = 14,        /*!< KaiTi.ttf */
};
