#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_I2S_MIC_GPIO_SCK  GPIO_NUM_38
#define AUDIO_I2S_MIC_GPIO_DIN  GPIO_NUM_39
#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_42
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_45
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_46
#define AUDIO_I2S_SPK_GPIO_GAIN GPIO_NUM_41

#define BUILTIN_LED_GPIO          GPIO_NUM_3
#define BOOT_BUTTON_GPIO          GPIO_NUM_0
#define TOUCH_BUTTON_GPIO         GPIO_NUM_NC
#define VOLUME_UP_BUTTON_GPIO     GPIO_NUM_NC
#define VOLUME_DOWN_BUTTON_GPIO   GPIO_NUM_NC
#define RESET_NVS_BUTTON_GPIO     GPIO_NUM_NC
#define RESET_FACTORY_BUTTON_GPIO GPIO_NUM_NC

// OLED (I2C)
#define DISPLAY_SDA_PIN GPIO_NUM_41
#define DISPLAY_SCL_PIN GPIO_NUM_42
#define DISPLAY_WIDTH   128
#define DISPLAY_HEIGHT  64
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y true

// 1 = SH1106, 0 = SSD1306
#define DISPLAY_USE_SH1106 1

#endif  // _BOARD_CONFIG_H_
