#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_4
#define AUDIO_I2S_GPIO_WS   GPIO_NUM_7
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_5
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_6
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_8

// IO1 低电平使能板载音频，需在板级初始化时立刻拉低
#define AUDIO_PA_ENABLE_PIN      GPIO_NUM_1
#define AUDIO_CODEC_PA_PIN       GPIO_NUM_NC
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_15
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_16
#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR

#define BUILTIN_LED_GPIO        GPIO_NUM_NC
#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_NC
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC

// 4 线 SPI 接口的 ST7796S 显示屏
#define DISPLAY_SPI_SCK_PIN  GPIO_NUM_12
#define DISPLAY_SPI_MOSI_PIN GPIO_NUM_11
#define DISPLAY_SPI_MISO_PIN GPIO_NUM_13
#define DISPLAY_DC_PIN       GPIO_NUM_46
#define DISPLAY_SPI_CS_PIN   GPIO_NUM_10
#define DISPLAY_SPI_MODE     0
#define DISPLAY_RST_PIN GPIO_NUM_NC

#define DISPLAY_BACKLIGHT_PIN          GPIO_NUM_45
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false


#define DISPLAY_WIDTH   320
#define DISPLAY_HEIGHT  480
#define DISPLAY_MIRROR_X     true
#define DISPLAY_MIRROR_Y     false
#define DISPLAY_SWAP_XY      false

#define DISPLAY_RGB_ORDER    LCD_RGB_ELEMENT_ORDER_BGR
#define DISPLAY_INVERT_COLOR true

#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 0

// FT6336U 电容触摸屏，与 ES8311、扩展 I2C 共用总线
#define TOUCH_RST_PIN GPIO_NUM_18
#define TOUCH_INT_PIN GPIO_NUM_17

#endif // _BOARD_CONFIG_H_
