#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#ifdef CONFIG_SD_CARD_MMC_INTERFACE
// Define to use 4-bit SDMMC bus width; comment out to use 1-bit bus width
#define CARD_SDMMC_BUS_WIDTH_4BIT

#ifdef CARD_SDMMC_BUS_WIDTH_4BIT
#define CARD_SDMMC_CLK_GPIO GPIO_NUM_38 // CLK pin
#define CARD_SDMMC_CMD_GPIO GPIO_NUM_40 // MISO pin
#define CARD_SDMMC_D0_GPIO  GPIO_NUM_39 // MOSI pin
#define CARD_SDMMC_D1_GPIO  GPIO_NUM_41
#define CARD_SDMMC_D2_GPIO  GPIO_NUM_48
#define CARD_SDMMC_D3_GPIO  GPIO_NUM_47  // CS pin
#else
#define CARD_SDMMC_CLK_GPIO GPIO_NUM_38
#define CARD_SDMMC_CMD_GPIO GPIO_NUM_40
#define CARD_SDMMC_D0_GPIO GPIO_NUM_39
#endif
#endif // CONFIG_SD_CARD_MMC_INTERFACE

#ifdef CONFIG_SD_CARD_SPI_INTERFACE
#define CARD_SPI_MOSI_GPIO GPIO_NUM_39
#define CARD_SPI_MISO_GPIO GPIO_NUM_40
#define CARD_SPI_SCLK_GPIO GPIO_NUM_38
#define CARD_SPI_CS_GPIO   GPIO_NUM_47
#endif // CONFIG_SD_CARD_SPI_INTERFACE

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_CODEC_PA_PIN GPIO_NUM_1
#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_4
#define AUDIO_I2S_GPIO_WS GPIO_NUM_7
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_5
#define AUDIO_I2S_GPIO_DIN GPIO_NUM_6
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_8
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_16
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_15
#define AUDIO_CODEC_ES8311_ADDR ES8311_CODEC_DEFAULT_ADDR
// #define AUDIO_CODEC_ES8311_ADDR 0x30  


#define BUILTIN_LED_GPIO        GPIO_NUM_48
#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define TOUCH_BUTTON_GPIO       GPIO_NUM_NC
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_NC
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_45
#define DISPLAY_MOSI_PIN      GPIO_NUM_11
#define DISPLAY_CLK_PIN       GPIO_NUM_12
#define DISPLAY_DC_PIN        GPIO_NUM_46
#define DISPLAY_RST_PIN       GPIO_NUM_NC
#define DISPLAY_CS_PIN        GPIO_NUM_10

#ifdef CONFIG_ES3N28P_LCD_ILI9341_240X320
#define LCD_TYPE_ILI9341_SERIAL
#define DISPLAY_WIDTH   240
#define DISPLAY_HEIGHT  320
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_INVERT_COLOR    true
#define DISPLAY_RGB_ORDER  LCD_RGB_ELEMENT_ORDER_BGR
#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_SPI_MODE 0
#endif

#ifdef CONFIG_ES3N28P_LCD_ILI9341_240X320_NO_IPS
#define LCD_TYPE_ILI9341_SERIAL
#define DISPLAY_WIDTH   240
#define DISPLAY_HEIGHT  320
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_INVERT_COLOR    false
#define DISPLAY_RGB_ORDER  LCD_RGB_ELEMENT_ORDER_BGR
#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_SPI_MODE 0
#endif

#ifdef CONFIG_ES3N28P_LCD_CUSTOM
#define DISPLAY_WIDTH   240
#define DISPLAY_HEIGHT  320
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_INVERT_COLOR    true
#define DISPLAY_RGB_ORDER  LCD_RGB_ELEMENT_ORDER_RGB
#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_SPI_MODE 0
#endif

// Touch (FT6236) I2C
#define TOUCH_SDA GPIO_NUM_16
#define TOUCH_SCL GPIO_NUM_15
#define TOUCH_RST GPIO_NUM_18
#define TOUCH_INT GPIO_NUM_17

// A MCP Test: Control a lamp
#define LAMP_GPIO GPIO_NUM_42

// Battery sense ADC
#define BATTERY_ADC_GPIO GPIO_NUM_9

#endif // _BOARD_CONFIG_H_
