#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 16000

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_4
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_5
#define AUDIO_I2S_GPIO_WS   GPIO_NUM_7
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_8
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_6
#define AUDIO_CODEC_PA_PIN  GPIO_NUM_1

#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_16
#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_15
#define AUDIO_CODEC_ES8311_ADDR 0x18

#define TOUCH_I2C_SDA_PIN AUDIO_CODEC_I2C_SDA_PIN
#define TOUCH_I2C_SCL_PIN AUDIO_CODEC_I2C_SCL_PIN
#define TOUCH_I2C_ADDRESS 0x38

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_45
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

#define DISPLAY_SPI_MOSI_PIN GPIO_NUM_11
#define DISPLAY_SPI_CLK_PIN  GPIO_NUM_12
#define DISPLAY_SPI_CS_PIN   GPIO_NUM_10
#define DISPLAY_SPI_DC_PIN   GPIO_NUM_46
#define DISPLAY_SPI_RESET_PIN GPIO_NUM_18

#define DISPLAY_WIDTH   240
#define DISPLAY_HEIGHT  320
#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0
#define DISPLAY_MIRROR_X  true
#define DISPLAY_MIRROR_Y  false
#define DISPLAY_SWAP_XY   false

#define BOOT_BUTTON_GPIO GPIO_NUM_0
#define BUILTIN_LED_GPIO GPIO_NUM_42
#define BATTERY_SENSE_GPIO GPIO_NUM_9

#endif // _BOARD_CONFIG_H_
