#ifndef __AOSL_HAL_CONFIG_H__
#define __AOSL_HAL_CONFIG_H__

#define AOSL_HAL_HAVE_EPOLL 0
#define AOSL_HAL_HAVE_POLL 0
#define AOSL_HAL_HAVE_SELECT 1

#define AOSL_HAL_HAVE_COND 1
#define AOSL_HAL_HAVE_SEM 0

#define AOSL_HAL_HAVE_HWRNG 1

#endif /* __AOSL_HAL_CONFIG_H__ */