#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_I2C

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_3
#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_0

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_7  //MCLK
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_11 //SCLK
#define AUDIO_I2S_GPIO_WS GPIO_NUM_9    //LRCK
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_8  //DSDIN
#define AUDIO_I2S_GPIO_DIN GPIO_NUM_10  //ASDOUT
#define AUDIO_CODEC_PA_PIN GPIO_NUM_2   //CTRL

#define AUDIO_CODEC_ES8311_ADDR ES8311_CODEC_DEFAULT_ADDR

#define POWER_GPIO              GPIO_NUM_6
#define BUILTIN_LED_GPIO        GPIO_NUM_5
#define BOOT_BUTTON_GPIO        GPIO_NUM_1
#define TOUCH_BUTTON_GPIO       GPIO_NUM_12
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_4
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_61

/*EPD port Init*/
#define EPD_SPI_NUM        SPI3_HOST

#define EPD_DC_PIN    GPIO_NUM_35
#define EPD_CS_PIN    GPIO_NUM_17
#define EPD_SCK_PIN   GPIO_NUM_34
#define EPD_MOSI_PIN  GPIO_NUM_33
#define EPD_RST_PIN   GPIO_NUM_14
#define EPD_BUSY_PIN  GPIO_NUM_13

#define DISPLAY_WIDTH   128
#define DISPLAY_HEIGHT  296

#endif // _BOARD_CONFIG_H_
