#ifndef _T_DECK_MAX_CONFIG_H_
#define _T_DECK_MAX_CONFIG_H_

#include <driver/gpio.h>
#include <driver/spi_common.h>

#define T_DECK_MAX_I2C_SDA GPIO_NUM_13
#define T_DECK_MAX_I2C_SCL GPIO_NUM_14

#define T_DECK_MAX_XL9555_ADDRESS 0x20
#define T_DECK_MAX_XL9555_AUDIO_SEL 10
#define T_DECK_MAX_XL9555_AMPLIFIER 6
#define T_DECK_MAX_XL9555_TOUCH_RESET 7
#define T_DECK_MAX_XL9555_KEYPAD_RESET 9

#define T_DECK_MAX_TOUCH_ADDRESS 0x1A
#define T_DECK_MAX_TOUCH_IRQ GPIO_NUM_12

#define T_DECK_MAX_KEYPAD_ADDRESS 0x34
#define T_DECK_MAX_KEYPAD_IRQ GPIO_NUM_15
#define T_DECK_MAX_KEYPAD_ROWS 4
#define T_DECK_MAX_KEYPAD_COLS 10

#define T_DECK_MAX_ES8311_ADDRESS 0x18
#ifndef ES8311_CODEC_DEFAULT_ADDR
#define ES8311_CODEC_DEFAULT_ADDR T_DECK_MAX_ES8311_ADDRESS
#endif
#define T_DECK_MAX_ES8311_MCLK GPIO_NUM_38
#define T_DECK_MAX_ES8311_BCLK GPIO_NUM_39
#define T_DECK_MAX_ES8311_LRCK GPIO_NUM_18
#define T_DECK_MAX_ES8311_DOUT GPIO_NUM_40
#define T_DECK_MAX_ES8311_DIN GPIO_NUM_17

#define T_DECK_MAX_EPD_WIDTH 240
#define T_DECK_MAX_EPD_HEIGHT 320
#define T_DECK_MAX_EPD_SCK GPIO_NUM_36
#define T_DECK_MAX_EPD_MOSI GPIO_NUM_33
#define T_DECK_MAX_EPD_DC GPIO_NUM_35
#define T_DECK_MAX_EPD_CS GPIO_NUM_34
#define T_DECK_MAX_EPD_BUSY GPIO_NUM_37
#define T_DECK_MAX_EPD_RST GPIO_NUM_9
#define T_DECK_MAX_EPD_BL GPIO_NUM_41
#define T_DECK_MAX_EPD_SPI_HOST SPI3_HOST

#define T_DECK_MAX_KEYBOARD_LED GPIO_NUM_42
#define T_DECK_MAX_SD_CS GPIO_NUM_48

#define AUDIO_INPUT_REFERENCE false
#define AUDIO_INPUT_SAMPLE_RATE 16000
#define AUDIO_OUTPUT_SAMPLE_RATE 16000

#define BOOT_BUTTON_GPIO GPIO_NUM_0
#define VOLUME_UP_BUTTON_GPIO GPIO_NUM_NC
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC

#endif  // _T_DECK_MAX_CONFIG_H_
