#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#if CONFIG_USE_DEVICE_AEC
#define AUDIO_INPUT_REFERENCE true
#else
#define AUDIO_INPUT_REFERENCE false
#endif

#define AUDIO_INPUT_SAMPLE_RATE 24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_11
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_10
#define AUDIO_I2S_GPIO_WS GPIO_NUM_8
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_7
#define AUDIO_I2S_GPIO_DIN GPIO_NUM_9

#define AUDIO_CODEC_PA_PIN GPIO_NUM_NC
#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_13
#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_12
#define AUDIO_CODEC_ES8311_ADDR ES8311_CODEC_DEFAULT_ADDR

#define BUILTIN_LED_GPIO GPIO_NUM_41
#define BOOT_BUTTON_GPIO GPIO_NUM_0
#define VOLUME_UP_BUTTON_GPIO GPIO_NUM_46
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_45
#define VOLUME_UP_BUTTON_EN_INVERT true
#define VOLUME_DOWN_BUTTON_EN_INVERT true

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_16
#define DISPLAY_MOSI_PIN GPIO_NUM_21
#define DISPLAY_CLK_PIN GPIO_NUM_17
#define DISPLAY_DC_PIN GPIO_NUM_14
#define DISPLAY_RST_PIN GPIO_NUM_NC
#define DISPLAY_CS_PIN GPIO_NUM_15

#define DISPLAY_WIDTH 240
#define DISPLAY_HEIGHT 240
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_INVERT_COLOR true
#define DISPLAY_RGB_ORDER LCD_RGB_ELEMENT_ORDER_RGB
#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 0
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_SPI_MODE 0

#define BATTERY_LEVEL_PIN GPIO_NUM_18
#define BATTERY_EN_PIN GPIO_NUM_NC
#define BATTERY_CHARGING_PIN GPIO_NUM_47

#endif // _BOARD_CONFIG_H_
