blank_issues_enabled: true
contact_links:
  - name: 小智 AI 官方网站
    url: https://xiaozhi.me/
    about: 激活设备、配置 AI、声纹识别、声音克隆等应有尽有，DIY 属于你自己的小智
  - name: 小智 AI 聊天机器人百科全书
    url: https://ccnphfhqs21z.feishu.cn/wiki/F5krwD16viZoF0kKkvDcrZNYnhb
    about: 开发文档、硬件制作、烧录教程、FAQ尽在小智百科