#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

// ES8311 audio codec and NS4150B speaker amplifier
#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_52
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_53
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_54
#define AUDIO_I2S_GPIO_WS   GPIO_NUM_55
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_56

#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_50
#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_51
#define AUDIO_CODEC_PA_PIN      GPIO_NUM_57
#define AUDIO_CODEC_ES8311_ADDR ES8311_CODEC_DEFAULT_ADDR

// On-board user controls
#define BUILTIN_LED_GPIO GPIO_NUM_60
#define BOOT_BUTTON_GPIO GPIO_NUM_61

#endif  // _BOARD_CONFIG_H_
