#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

// 音频
#define AUDIO_INPUT_SAMPLE_RATE 24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_10
#define AUDIO_I2S_GPIO_WS GPIO_NUM_6
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_8
#define AUDIO_I2S_GPIO_DIN GPIO_NUM_7
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_5

#define AUDIO_CODEC_PA_PIN GPIO_NUM_11  
#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_3
#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_4
#define AUDIO_CODEC_ES8311_ADDR ES8311_CODEC_DEFAULT_ADDR 

// 按键
#define BOOT_BUTTON_GPIO GPIO_NUM_9

// 电源管理
#define POWER_USB_IN GPIO_NUM_1
#define Power_Control GPIO_NUM_21
#define Power_Dec GPIO_NUM_2
#define POWER_CBS_ADC_UNIT ADC_UNIT_1   // adc检测公共unit
#define POWER_USBIN_ADC_CHANNEL ADC_CHANNEL_1 // 检测usb是否插入 
#define POWER_BATTERY_ADC_CHANNEL ADC_CHANNEL_0 // 电池电量检测

#endif // _BOARD_CONFIG_H_
