#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define RIGHT_LEG_PIN GPIO_NUM_11
#define RIGHT_FOOT_PIN GPIO_NUM_14
#define LEFT_LEG_PIN GPIO_NUM_13
#define LEFT_FOOT_PIN GPIO_NUM_12
#define LEFT_HAND_PIN GPIO_NUM_21
#define RIGHT_HAND_PIN GPIO_NUM_10

#define AUDIO_INPUT_SAMPLE_RATE 16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000
#define AUDIO_I2S_METHOD_SIMPLEX

#define AUDIO_I2S_MIC_GPIO_WS   GPIO_NUM_40
#define AUDIO_I2S_MIC_GPIO_SCK  GPIO_NUM_39
#define AUDIO_I2S_MIC_GPIO_DIN  GPIO_NUM_41
#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_47
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_48
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_45

#define TOUCH_BUTTON_GPIO       GPIO_NUM_14
#define BOOT_BUTTON_GPIO GPIO_NUM_38

#define EDA_SUPER_BEAR_VERSION "1.0.0"

#endif  // _BOARD_CONFIG_H_
