#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_INPUT_REFERENCE    true

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_38
#define AUDIO_I2S_GPIO_WS GPIO_NUM_13
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_14
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_11
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_12

#define AUDIO_CODEC_PA_PIN       GPIO_NUM_42
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_1
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_2
#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR
#define AUDIO_CODEC_ES7210_ADDR  0x82  // ES7210 I2C address (0x41 << 1)


#define BUILTIN_LED_GPIO        GPIO_NUM_10
#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define PWR_BUTTON_GPIO         GPIO_NUM_3
#define PWR_EN_GPIO             GPIO_NUM_15
#define VBAT_ADC_GPIO           GPIO_NUM_4  // 电池电压监测引脚（通过分压电路）
#define VBUS_ADC_GPIO           GPIO_NUM_5  // USB电压监测引脚（用于充电检测）
#define BATTERY_FULL_PIN        GPIO_NUM_16 // LGS4056HEP DONE引脚（电池充满检测，低电平=充满）
#define PWR_BUTTON_TIME         3000000U

#define WIFI_BUTTON_GPIO        GPIO_NUM_6
#define CMD_BUTTON_GPIO         GPIO_NUM_7


#define DISPLAY_SPI_SCK_PIN     GPIO_NUM_41
#define DISPLAY_SPI_MOSI_PIN    GPIO_NUM_40
#define DISPLAY_DC_PIN          GPIO_NUM_39
#define DISPLAY_SPI_CS_PIN      GPIO_NUM_9

#define DISPLAY_WIDTH   240
#define DISPLAY_HEIGHT  320
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false

#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_46
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

#define ML307_TX_PIN GPIO_NUM_17
#define ML307_RX_PIN GPIO_NUM_18  
#define ML307_POWER_PIN GPIO_NUM_45
#define ML307_POWER_OUTPUT_INVERT false

// LCD驱动类型配置
// 通过 Kconfig 配置: menuconfig -> 九川S3配置 -> LCD驱动类型
// 1 = GC9301/GC9309NA
// 2 = JD9853
#if defined(CONFIG_JIUCHUAN_LCD_JD9853)
    #define LCD_DRIVER_TYPE  2
#else
    #define LCD_DRIVER_TYPE  1  // 默认或 CONFIG_JIUCHUAN_LCD_GC9301
#endif

#endif // _BOARD_CONFIG_H_
