
#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE 24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

// 音频
#define AUDIO_I2S_GPIO_WS   GPIO_NUM_4
#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_5
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_6
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_15
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_17

#define AUDIO_CODEC_PA_PIN      GPIO_NUM_21  
#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_41
#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_42
#define AUDIO_CODEC_ES8311_ADDR (0x30) 

// 按键
#define BOOT_BUTTON_GPIO    GPIO_NUM_8

// 电源管理
#define POWER_USB_IN            GPIO_NUM_1
#define POWER_DEC               GPIO_NUM_39
#define POWER_CONTROL           GPIO_NUM_47
#define POWER_BARRY_ADC_UNIT    ADC_UNIT_1
#define POWER_USB_ADC_CHANNEL   ADC_CHANNEL_0   // usb插入检测ADC通道 GPIO1
#define POWER_BARRY_ADC_CHANNEL ADC_CHANNEL_6   // 电池电量检测ADC通道 GPIO7

#endif // _BOARD_CONFIG_H_
