set(CMAKE_SYSTEM_NAME Linux) # set system name
set(CMAKE_FIND_ROOT_PATH "") # set toolchain dir
set(CONFIG_TOOLCHAIN_PREFIX "") # set toolchain prefix
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_C_COMPILER   "${CMAKE_FIND_ROOT_PATH}${CONFIG_TOOLCHAIN_PREFIX}gcc")
set(CMAKE_CXX_COMPILER "${CMAKE_FIND_ROOT_PATH}${CONFIG_TOOLCHAIN_PREFIX}g++")
set(CMAKE_ASM_COMPILER "${CMAKE_FIND_ROOT_PATH}${CONFIG_TOOLCHAIN_PREFIX}as")
set(CMAKE_AR "${CMAKE_FIND_ROOT_PATH}${CONFIG_TOOLCHAIN_PREFIX}ar")
set(CMAKE_LD "${CMAKE_FIND_ROOT_PATH}${CONFIG_TOOLCHAIN_PREFIX}ld")
set(CMAKE_NM "${CMAKE_FIND_ROOT_PATH}${CONFIG_TOOLCHAIN_PREFIX}nm")
set(CMAKE_C_FLAGS_DEBUG "$ENV{CFLAGS} -DDEBUG -g -fPIC")
set(CMAKE_C_FLAGS_RELEASE "$ENV{CFLAGS} -Os -DNDEBUG -g -fPIC")