esp_toml_version = 1.0
firmware_images_url = "https://raw.githubusercontent.com/whble/xiaozhi-esp32/refs/heads/main/images/"
config_readme_url = "https://raw.githubusercontent.com/whble/xiaozhi-esp32/refs/heads/main/images/cfg.md"

supported_apps = ["xiaozhi_esp-box-3_v0_9_8"]

[xiaozhi_esp-box-3_v0_9_8]
chipsets = ["ESP32S3"]
image.esp32s3 = "xiaozhi_esp-box-3_v0_9_8.bin"
ios_app_url = ""
android_app_url = ""
readme.text = "https://raw.githubusercontent.com/78/xiaozhi-esp32/refs/heads/main/README.md"

