// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: eye_asset_250730

#ifndef _EYE_ASSET_250730_UI_H
#define _EYE_ASSET_250730_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_defaultStandBy.h"
#include "screens/ui_talking.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * eyeblink_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * mouthTalking_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_background_black_png);    // assets/backGround_black.png
LV_IMG_DECLARE(ui_img_eye_blink_01_png);    // assets/eye_blink_01.png
LV_IMG_DECLARE(ui_img_eff_rouge_png);    // assets/eff_rouge.png
LV_IMG_DECLARE(ui_img_mouth_standby_png);    // assets/mouth_standBy.png
LV_IMG_DECLARE(ui_img_mouth_talking_01_png);    // assets/mouth_talking_01.png
LV_IMG_DECLARE(ui_img_eye_blink_02_png);    // assets/eye_blink_02.png
LV_IMG_DECLARE(ui_img_eye_blink_03_png);    // assets/eye_blink_03.png
LV_IMG_DECLARE(ui_img_eye_blink_04_png);    // assets/eye_blink_04.png
LV_IMG_DECLARE(ui_img_eye_blink_05_png);    // assets/eye_blink_05.png
LV_IMG_DECLARE(ui_img_eye_blink_06_png);    // assets/eye_blink_06.png
LV_IMG_DECLARE(ui_img_eye_blink_07_png);    // assets/eye_blink_07.png
LV_IMG_DECLARE(ui_img_eye_blink_08_png);    // assets/eye_blink_08.png
LV_IMG_DECLARE(ui_img_eye_blink_09_png);    // assets/eye_blink_09.png
LV_IMG_DECLARE(ui_img_eye_blink_10_png);    // assets/eye_blink_10.png
LV_IMG_DECLARE(ui_img_mouth_talking_02_png);    // assets/mouth_talking_02.png
LV_IMG_DECLARE(ui_img_mouth_talking_03_png);    // assets/mouth_talking_03.png
LV_IMG_DECLARE(ui_img_mouth_talking_04_png);    // assets/mouth_talking_04.png
LV_IMG_DECLARE(ui_img_mouth_talking_05_png);    // assets/mouth_talking_05.png
LV_IMG_DECLARE(ui_img_mouth_talking_06_png);    // assets/mouth_talking_06.png
LV_IMG_DECLARE(ui_img_mouth_talking_07_png);    // assets/mouth_talking_07.png
LV_IMG_DECLARE(ui_img_mouth_talking_08_png);    // assets/mouth_talking_08.png
LV_IMG_DECLARE(ui_img_mouth_talking_09_png);    // assets/mouth_talking_09.png
LV_IMG_DECLARE(ui_img_mouth_talking_10_png);    // assets/mouth_talking_10.png
LV_IMG_DECLARE(ui_img_mouth_talking_11_png);    // assets/mouth_talking_11.png
LV_IMG_DECLARE(ui_img_mouth_talking_12_png);    // assets/mouth_talking_12.png
LV_IMG_DECLARE(ui_img_mouth_talking_13_png);    // assets/mouth_talking_13.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
