#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>
#include <driver/spi_master.h>

#define AUDIO_INPUT_SAMPLE_RATE 24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_8
#define AUDIO_I2S_GPIO_WS GPIO_NUM_10
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_9
#define AUDIO_I2S_GPIO_DIN GPIO_NUM_11
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_12

#define AUDIO_CODEC_PA_PIN GPIO_NUM_7
#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_42
#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_41
#define AUDIO_CODEC_ES8311_ADDR ES8311_CODEC_DEFAULT_ADDR
#define AUDIO_CODEC_ES7210_ADDR ES7210_CODEC_DEFAULT_ADDR

#define BUILTIN_LED_GPIO GPIO_NUM_48
#define PWR_BUTTON_GPIO GPIO_NUM_5
#define VOLUME_UP_BUTTON_GPIO GPIO_NUM_4
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_0

#define DISPLAY_SPI_MODE 3
#define DISPLAY_CS_PIN GPIO_NUM_21
#define DISPLAY_MOSI_PIN GPIO_NUM_39
#define DISPLAY_MISO_PIN GPIO_NUM_NC
#define DISPLAY_CLK_PIN GPIO_NUM_38
#define DISPLAY_DC_PIN GPIO_NUM_45
#define DISPLAY_RST_PIN GPIO_NUM_40

#define TOOUCH_INT_PIN GPIO_NUM_48
#define TOOUCH_RST_PIN GPIO_NUM_47

#define BATTERY_EN_PIN GPIO_NUM_2
#define BATTERY_ADC_PIN GPIO_NUM_1
#define BATTERY_CHARGING_PIN GPIO_NUM_3

#define DISPLAY_WIDTH 128
#define DISPLAY_HEIGHT 128
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y true
#define DISPLAY_SWAP_XY false
#define DISPLAY_RGB_ORDER LCD_RGB_ELEMENT_ORDER_BGR
#define DISPLAY_INVERT_COLOR true

#define DISPLAY_OFFSET_X 2
#define DISPLAY_OFFSET_Y 1

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_46
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

#endif // _BOARD_CONFIG_H_
