#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

// Audio configuration (ES8311 codec)
#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_4
#define AUDIO_I2S_GPIO_WS   GPIO_NUM_7
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_5
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_6
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_8

#define AUDIO_CODEC_PA_PIN       GPIO_NUM_1
#define AUDIO_CODEC_PA_PIN_INVERT true
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_16
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_15
#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR

// Button
#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_NC
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC

// WS2812B RGB LED
#define BUILTIN_LED_GPIO        GPIO_NUM_42

// Display configuration (ILI9341V, SPI, 240x320)
#define DISPLAY_SPI_MOSI_PIN    GPIO_NUM_11
#define DISPLAY_SPI_MISO_PIN    GPIO_NUM_13
#define DISPLAY_SPI_SCK_PIN     GPIO_NUM_12
#define DISPLAY_SPI_CS_PIN      GPIO_NUM_10
#define DISPLAY_DC_PIN          GPIO_NUM_46
#define DISPLAY_RST_PIN         GPIO_NUM_NC

#define DISPLAY_WIDTH   320
#define DISPLAY_HEIGHT  240
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y true
#define DISPLAY_SWAP_XY true

#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_45
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

// Touch configuration (FT6336G, I2C)
#define TOUCH_I2C_SDA_PIN  GPIO_NUM_16
#define TOUCH_I2C_SCL_PIN  GPIO_NUM_15
#define TOUCH_RST_PIN      GPIO_NUM_18
#define TOUCH_INT_PIN      GPIO_NUM_17
#define TOUCH_I2C_ADDR     0x38

// Battery ADC
#define BATTERY_ADC_PIN    GPIO_NUM_9

#endif // _BOARD_CONFIG_H_
