.github/workflows/build.yml

name: Build ESP32-C6 AI Terminal

on:
  push:
    branches:
      - "**"

jobs:

  prepare:
    outputs:
      variants: ...

  build:
    needs: prepare

    matrix:
      include:
        - board:
            waveshare/esp32-c6-dev-kit-n16-ai-terminal
          name:
            esp32-c6-dev-kit-n16-ai-terminal

    build:
      python scripts/build.py \
      waveshare/esp32-c6-dev-kit-n16-ai-terminal \
      --name esp32-c6-dev-kit-n16-ai-terminal

    upload:
      build/merged-binary.bin
