#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#ifndef BOARD_NAME
#define BOARD_NAME "ESP32-C3 Super Mini"
#endif

// Audio sample rates
#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000
#define AUDIO_I2S_METHOD_SIMPLEX

// Speaker I2S pins (MAX98357A)
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_7
#define AUDIO_I2S_SPK_GPIO_WS   GPIO_NUM_5
#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_6

// Microphone I2S pins (INMP441)
#define AUDIO_I2S_MIC_GPIO_SCK  GPIO_NUM_3
#define AUDIO_I2S_MIC_GPIO_WS   GPIO_NUM_2
#define AUDIO_I2S_MIC_GPIO_DIN  GPIO_NUM_4

#define DISPLAY_SDA_PIN GPIO_NUM_8
#define DISPLAY_SCL_PIN GPIO_NUM_9
#define DISPLAY_I2C_ADDR 0x3C
#define DISPLAY_WIDTH    128
#define DISPLAY_HEIGHT   64

// Rotate 180°
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y true
#define DISPLAY_SWAP_XY false

#define BUILTIN_LED_GPIO GPIO_NUM_NC
#define BOOT_BUTTON_GPIO GPIO_NUM_NC

#endif // _BOARD_CONFIG_H_
