#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define PIN_BATT_MON        GPIO_NUM_13    	//检测PMU电池指示

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000
#define AUDIO_DEFAULT_OUTPUT_VOLUME 80

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_10
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_8
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_3
#define AUDIO_I2S_GPIO_WS   GPIO_NUM_2
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_0

#define AUDIO_CODEC_PA_PIN       GPIO_NUM_11
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_20
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_21
// #define AUDIO_CODEC_ES8311_ADDR  0x18u
#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR

#define BOOT_BUTTON_GPIO        GPIO_NUM_1
#define BOOT_5V_GPIO            GPIO_NUM_9

#define DISPLAY_SPI_LCD_HOST    SPI2_HOST
#define DISPLAY_SPI_CLOCK_HZ    (40 * 1000 * 1000)
#define DISPLAY_SPI_PIN_SCLK    6
#define DISPLAY_SPI_PIN_MOSI    4
#define DISPLAY_SPI_PIN_MISO    -1
#define DISPLAY_SPI_PIN_LCD_DC  5
#define DISPLAY_SPI_PIN_LCD_RST 7
#define DISPLAY_SPI_PIN_LCD_CS  -1
#define DISPLAY_PIN_TOUCH_CS    -1

#define DISPLAY_BACKLIGHT_PIN   GPIO_NUM_12
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

#define DISPLAY_WIDTH   320
#define DISPLAY_HEIGHT  240
#define DISPLAY_SWAP_XY true
#if CONFIG_LCD_CONTROLLER_ILI9341
    #define DISPLAY_MIRROR_X true
    #define DISPLAY_MIRROR_Y true
    #define DISPLAY_INVERT_COLOR false
    #define DISPLAY_RGB_ORDER_COLOR LCD_RGB_ELEMENT_ORDER_BGR
#elif CONFIG_LCD_CONTROLLER_ST7789
    #define DISPLAY_MIRROR_X false
    #define DISPLAY_MIRROR_Y true
    #define DISPLAY_INVERT_COLOR false
    #define DISPLAY_RGB_ORDER_COLOR LCD_RGB_ELEMENT_ORDER_RGB
#endif

#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0


#endif // _BOARD_CONFIG_H_
